import Head from 'next/head'
import Header from '../components/Header'
import {Row,Col,List,Avatar } from 'antd'
import { useState } from 'react'
import {CalendarOutlined,FolderOpenOutlined,FireOutlined} from "@ant-design/icons"
import Author from '../components/Author'
import Ads from '../components/Ads'
import Footer from '../components/Footer'
import axios from "axios"
import Link from 'next/link'
import  servicePath  from '../config/apiUrl'

import marked from "marked" // using for parse markdown text
import hljs from "highlight.js"// hight your code here
import 'highlight.js/styles/monokai-sublime.css';


 const Home=(results)=> {
   //console.log("results---",results)
   const [list,setList]=useState(results.data)
   const [selflist,setSelfList]=useState(list)

   const renderer = new marked.Renderer();
   marked.setOptions({
    renderer: renderer, 
    gfm: true,
    pedantic: false,
    sanitize: false,
    tables: true,
    breaks: false,
    smartLists: true,
    smartypants: false,
    highlight: (code) => {
      return hljs.highlightAuto(code).value;
    }
  }); 

  return (
    
    <div>
      <Head>
        <title>BLOG...</title>
        <meta name="description" content="Generated by create next app" />
        <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header list={list} setSelfList={setSelfList}/>  
      <Row className="comm-main" type="flex" justify="center">
        <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}  >
          <List 
            header={<h3>Latest 10 Articles</h3>}
            itemLayout="vertical"
            dataSource={selflist}
            renderItem={item => (
              <List.Item>
                <div className="list-title">
                  <Link href={{
                      pathname:"/detailed",
                      query:{
                        id:item.id
                      }
                    }}><a>{item.title}</a></Link>
                </div>
                <div className="list-icon">
                    <span><CalendarOutlined />  {item.addTime}  </span>
                    <span><FolderOpenOutlined />  {item.typeName}  </span>
                    <span><FireOutlined />  {item.view_count} </span>
                </div>
                <div className="list-context" 
                dangerouslySetInnerHTML={{__html:marked(item.introduce)}}
                ></div>
              </List.Item>
            )}
          />
        </Col>

        <Col className="comm-right" xs={0} sm={0} md={7} lg={5} xl={4}>
          <Author />
          <Ads />
        </Col>
      </Row>
      <Footer />
    </div>
    
  )
}

Home.getInitialProps=async()=>{
  const promise=new Promise((resolve)=>{
      axios(servicePath.getArticleList).then(
          (res)=>{
              resolve(res.data)
          }
      )
  })
  return await promise;
}

export default Home;

